[project]
name = "turbotorrent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bencode-py>=4.0.0",
    "httpx>=0.28.1",
    "ruff>=0.12.2",
]
